const {execFileSync, spawnSync} = require('node:child_process');
const {readFileSync, rmSync, writeFileSync} = require('node:fs');
const {resolve} = require('node:path');

const projectRoot = resolve(__dirname, '..');
const packageJson = JSON.parse(readFileSync(resolve(projectRoot, 'package.json'), 'utf8'));

function git(...args) {
  return execFileSync('git', args, {
    cwd: projectRoot,
    encoding: 'utf8',
  }).trim();
}

const buildInfo = {
  version: `v${packageJson.version}`,
  commit: git('rev-parse', 'HEAD').slice(0, 6),
  isDirty: git('status', '--porcelain', '--untracked-files=normal').length > 0,
};

const generatedPath = resolve(projectRoot, 'build-info.generated.ts');

try {
  writeFileSync(
    generatedPath,
    `// Generated by scripts/build.cjs during pnpm build.\n` +
      `export const buildInfo = ${JSON.stringify(buildInfo, null, 2)} as const;\n`,
  );

  const result = spawnSync(process.execPath, [require.resolve('typescript/bin/tsc')], {
    cwd: projectRoot,
    stdio: 'inherit',
  });
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    process.exitCode = result.status ?? 1;
  }
} finally {
  rmSync(generatedPath, {force: true});
}
